apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: approval-test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  approve_me:
    with:
      instructions: ""
      disallowLaunchByUser: false
      approvers: cbibin@cloudbees.com
      notifyAllEligibleUsers: false
    timeout-minutes: 10
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
 
  build:
    needs:
      - approve_me
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"

  deploy:
    needs:
      - build
    environment: preprod-us-east-1
    steps:
      - name: Deploy step
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "deploying to prod"
 
