apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - id: build-image
        kind: build
        name: Build Go Application
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Building Go application"
          echo "hello world" > hello.txt
          # Simulate building a Go app
          # Build your Go application or run your build scripts here
          echo "Build successful"
      
  deploy:
    steps:
      - id: deploy-image
        kind: deploy
        environment: staging
        name: Deploy Go Application
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Deploying Go application"
          # Simulate deployment (e.g., copy files, run deployment scripts, etc.)
          echo "Deployed successfully"
