apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "branchtest3"
  workflow_dispatch:
jobs:
  build:
    steps:
      - id: build-image
        kind: build
        name: Build Go Application
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Building Go application"
          echo "hello world" > hello.txt
          # Simulate building a Go app
          # Build your Go application or run your build scripts here
          echo "Build successful"
      
  deploy-east-1:
    environment: preprod-us-east-1
    steps:
      - id: deploy-step
        kind: deploy
        name: Deploy Go Application
        uses: docker://alpine:3.17
        shell: sh
        run: |
          echo "Deploying Go application to preprod-us-east-1"
          echo "hello world" # You can add actual deployment commands here
          # Simulate deployment (e.g., copy files, push Docker image, etc.)
          echo "Deployed successfully to preprod-us-east-1"

   
       